import {
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname } from "node:path";
import {
  CONFIG_DIR,
  AUTO_PUSH_SCRIPT_FILE,
  AUTO_PUSH_LOG_FILE,
  AUTO_PUSH_LOG_KEEP_LINES,
  AUTO_PUSH_LOG_MAX_BYTES,
  LAUNCHD_PLIST_PATH,
  CLI_VERSION,
} from "../config.js";
import {
  durableBackgroundInvocation,
  shellQuote,
} from "./background-command.js";

const CRON_TAG = "# straude-auto-push";
const LAUNCHD_LABEL = "com.straude.auto-push";

export function detectScheduler(): "launchd" | "cron" {
  return process.platform === "darwin" ? "launchd" : "cron";
}

function launchdDomain(): string {
  const uid = process.getuid?.();
  if (uid == null) throw new Error("Unable to determine the current user for launchd.");
  return `gui/${uid}`;
}

function launchdService(): string {
  return `${launchdDomain()}/${LAUNCHD_LABEL}`;
}

function run(
  command: string,
  args: string[],
  options: { input?: string; ignoreFailure?: boolean } = {},
): string {
  try {
    return execFileSync(command, args, {
      encoding: "utf-8",
      input: options.input,
      stdio: options.input == null ? ["ignore", "pipe", "pipe"] : ["pipe", "pipe", "pipe"],
    });
  } catch (error) {
    if (options.ignoreFailure) return "";
    const detail = (error as { stderr?: string | Buffer }).stderr?.toString().trim();
    throw new Error(
      `${command} ${args.join(" ")} failed${detail ? `: ${detail}` : ""}`,
      { cause: error },
    );
  }
}

function readCrontab(): string | null {
  try {
    return run("crontab", ["-l"]);
  } catch {
    return null;
  }
}

export function isSchedulerInstalled(scheduler: "launchd" | "cron"): boolean {
  if (scheduler === "launchd") {
    if (!existsSync(LAUNCHD_PLIST_PATH)) return false;
    try {
      run("launchctl", ["print", launchdService()]);
      return true;
    } catch {
      return false;
    }
  }
  return readCrontab()?.includes(CRON_TAG) ?? false;
}

function parseTime(time: string): { hour: number; minute: number } {
  const match = time.match(/^(\d{1,2}):(\d{2})$/);
  if (!match) throw new Error(`Invalid time format: ${time}. Use HH:MM (e.g., 09:00, 14:30).`);
  const hour = parseInt(match[1]!, 10);
  const minute = parseInt(match[2]!, 10);
  if (hour < 0 || hour > 23) throw new Error(`Invalid hour: ${hour}. Must be 0-23.`);
  if (minute < 0 || minute > 59) throw new Error(`Invalid minute: ${minute}. Must be 0-59.`);
  return { hour, minute };
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildWrapperScript(): string {
  const userPath = process.env.PATH ?? "";
  const durable = durableBackgroundInvocation();
  const runner = durable
    ? `exec ${[durable.executable, ...durable.args, "push", "--non-interactive"]
      .map(shellQuote)
      .join(" ")}`
    : `if command -v bunx >/dev/null 2>&1; then
  exec bunx straude@${CLI_VERSION} push --non-interactive
elif command -v npx >/dev/null 2>&1; then
  exec npx --yes straude@${CLI_VERSION} push --non-interactive
else
  echo "[$TIMESTAMP] ERROR: Cannot find bunx or npx on PATH"
  exit 1
fi`;
  return `#!/bin/sh
# Generated by straude --auto. Do not edit.
PATH=${shellQuote(`/usr/local/bin:/opt/homebrew/bin:${userPath}`)}
export PATH
LOG_FILE=${shellQuote(AUTO_PUSH_LOG_FILE)}
LOG_TMP="\${LOG_FILE}.tmp.$$"

if [ -f "$LOG_FILE" ] && [ "$(wc -c < "$LOG_FILE")" -gt ${AUTO_PUSH_LOG_MAX_BYTES} ]; then
  tail -n ${AUTO_PUSH_LOG_KEEP_LINES} "$LOG_FILE" > "$LOG_TMP" && mv "$LOG_TMP" "$LOG_FILE"
fi
rm -f "$LOG_TMP"
exec >> "$LOG_FILE" 2>&1

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
echo "[$TIMESTAMP] Auto-push starting..."

${runner}
`;
}

function buildPlist(hour: number, minute: number): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${xmlEscape(AUTO_PUSH_SCRIPT_FILE)}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>${hour}</integer>
    <key>Minute</key>
    <integer>${minute}</integer>
  </dict>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
`;
}

function writeWrapperScript(): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  }
  writeFileSync(AUTO_PUSH_SCRIPT_FILE, buildWrapperScript(), { encoding: "utf-8", mode: 0o755 });
}

function restoreFile(
  path: string,
  previous: string | null,
  options?: { encoding: "utf-8"; mode?: number },
): void {
  if (previous === null) {
    if (existsSync(path)) unlinkSync(path);
    return;
  }
  writeFileSync(path, previous, options ?? { encoding: "utf-8" });
}

function installLaunchd(hour: number, minute: number): void {
  const launchdDir = dirname(LAUNCHD_PLIST_PATH);
  if (!existsSync(launchdDir)) mkdirSync(launchdDir, { recursive: true });

  const previousWrapper = existsSync(AUTO_PUSH_SCRIPT_FILE)
    ? readFileSync(AUTO_PUSH_SCRIPT_FILE, "utf8")
    : null;
  const previousPlist = existsSync(LAUNCHD_PLIST_PATH)
    ? readFileSync(LAUNCHD_PLIST_PATH, "utf8")
    : null;
  const previousActive = previousPlist !== null
    && run("launchctl", ["print", launchdService()], { ignoreFailure: true }).length > 0;
  try {
    writeWrapperScript();
    writeFileSync(LAUNCHD_PLIST_PATH, buildPlist(hour, minute), { encoding: "utf-8" });
    run("launchctl", ["bootout", launchdDomain(), LAUNCHD_PLIST_PATH], {
      ignoreFailure: true,
    });
    run("launchctl", ["bootstrap", launchdDomain(), LAUNCHD_PLIST_PATH]);
    run("launchctl", ["print", launchdService()]);
  } catch (error) {
    run("launchctl", ["bootout", launchdDomain(), LAUNCHD_PLIST_PATH], {
      ignoreFailure: true,
    });
    restoreFile(
      AUTO_PUSH_SCRIPT_FILE,
      previousWrapper,
      { encoding: "utf-8", mode: 0o755 },
    );
    restoreFile(LAUNCHD_PLIST_PATH, previousPlist);
    if (previousActive && previousPlist !== null) {
      run("launchctl", ["bootstrap", launchdDomain(), LAUNCHD_PLIST_PATH], {
        ignoreFailure: true,
      });
    }
    throw error;
  }
}

function cronEntry(hour: number, minute: number): string {
  return `${minute} ${hour} * * * ${shellQuote(AUTO_PUSH_SCRIPT_FILE)} ${CRON_TAG}`;
}

function installCron(hour: number, minute: number): void {
  const previousWrapper = existsSync(AUTO_PUSH_SCRIPT_FILE)
    ? readFileSync(AUTO_PUSH_SCRIPT_FILE, "utf8")
    : null;
  const existing = readCrontab() ?? "";
  const filtered = existing
    .split("\n")
    .filter((line) => !line.includes(CRON_TAG))
    .join("\n");
  const prefix = filtered.trimEnd();
  const newCrontab = `${prefix}${prefix ? "\n" : ""}${cronEntry(hour, minute)}\n`;
  try {
    writeWrapperScript();
    run("crontab", ["-"], { input: newCrontab });
    if (readCrontab()?.includes(cronEntry(hour, minute))) return;
    throw new Error("Cron accepted the update but the Straude entry was not active.");
  } catch (error) {
    if (existing.trim() === "") run("crontab", ["-r"], { ignoreFailure: true });
    else run("crontab", ["-"], { input: existing.endsWith("\n") ? existing : `${existing}\n` });
    restoreFile(
      AUTO_PUSH_SCRIPT_FILE,
      previousWrapper,
      { encoding: "utf-8", mode: 0o755 },
    );
    throw error;
  }
}

function uninstallLaunchd(): void {
  if (existsSync(LAUNCHD_PLIST_PATH)) {
    run("launchctl", ["bootout", launchdDomain(), LAUNCHD_PLIST_PATH], {
      ignoreFailure: true,
    });
    unlinkSync(LAUNCHD_PLIST_PATH);
  }
  if (existsSync(AUTO_PUSH_SCRIPT_FILE)) unlinkSync(AUTO_PUSH_SCRIPT_FILE);
}

function uninstallCron(): void {
  const existing = readCrontab();
  if (existing == null || !existing.includes(CRON_TAG)) return;

  const filtered = existing
    .split("\n")
    .filter((line) => !line.includes(CRON_TAG))
    .join("\n")
    .trimEnd();
  if (filtered === "") {
    run("crontab", ["-r"], { ignoreFailure: true });
  } else {
    run("crontab", ["-"], { input: `${filtered}\n` });
  }
  if (existsSync(AUTO_PUSH_SCRIPT_FILE)) unlinkSync(AUTO_PUSH_SCRIPT_FILE);
}

export function installScheduler(time: string, scheduler: "launchd" | "cron"): void {
  const { hour, minute } = parseTime(time);
  if (scheduler === "launchd") installLaunchd(hour, minute);
  else installCron(hour, minute);
}

export function uninstallScheduler(scheduler: "launchd" | "cron"): void {
  if (scheduler === "launchd") uninstallLaunchd();
  else uninstallCron();
}

export { parseTime as _parseTime, buildWrapperScript as _buildWrapperScript, buildPlist as _buildPlist };
