import { existsSync, readFileSync, writeFileSync, unlinkSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname } from "node:path";
import {
  CONFIG_DIR,
  AUTO_PUSH_SCRIPT_FILE,
  AUTO_PUSH_LOG_FILE,
  LAUNCHD_PLIST_PATH,
} from "../config.js";

const CRON_TAG = "# straude-auto-push";

export function detectScheduler(): "launchd" | "cron" {
  return process.platform === "darwin" ? "launchd" : "cron";
}

export function isSchedulerInstalled(scheduler: "launchd" | "cron"): boolean {
  if (scheduler === "launchd") {
    return existsSync(LAUNCHD_PLIST_PATH);
  }
  // cron: check if tagged entry exists in crontab
  try {
    const crontab = execSync("crontab -l 2>/dev/null", { encoding: "utf-8" });
    return crontab.includes(CRON_TAG);
  } catch {
    return false;
  }
}

function parseTime(time: string): { hour: number; minute: number } {
  const match = time.match(/^(\d{1,2}):(\d{2})$/);
  if (!match) throw new Error(`Invalid time format: ${time}. Use HH:MM (e.g., 09:00, 14:30).`);
  const hour = parseInt(match[1]!, 10);
  const minute = parseInt(match[2]!, 10);
  if (hour < 0 || hour > 23) throw new Error(`Invalid hour: ${hour}. Must be 0-23.`);
  if (minute < 0 || minute > 59) throw new Error(`Invalid minute: ${minute}. Must be 0-59.`);
  return { hour, minute };
}

function buildWrapperScript(): string {
  const userPath = process.env.PATH ?? "";
  return `#!/bin/sh
# Generated by straude --auto — do not edit
export PATH="/usr/local/bin:/opt/homebrew/bin:${userPath}"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
echo "[$TIMESTAMP] Auto-push starting..."

if command -v straude >/dev/null 2>&1; then
  straude push 2>&1
elif command -v bunx >/dev/null 2>&1; then
  bunx straude@latest push 2>&1
elif command -v npx >/dev/null 2>&1; then
  npx --yes straude@latest push 2>&1
else
  echo "[$TIMESTAMP] ERROR: Cannot find straude, bunx, or npx on PATH"
  exit 1
fi

EXIT_CODE=$?
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
[ $EXIT_CODE -eq 0 ] && echo "[$TIMESTAMP] Auto-push completed" || echo "[$TIMESTAMP] Auto-push failed (exit $EXIT_CODE)"
`;
}

function buildPlist(hour: number, minute: number): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.straude.auto-push</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${AUTO_PUSH_SCRIPT_FILE}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>${hour}</integer>
    <key>Minute</key>
    <integer>${minute}</integer>
  </dict>
  <key>StandardOutPath</key>
  <string>${AUTO_PUSH_LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${AUTO_PUSH_LOG_FILE}</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
`;
}

function writeWrapperScript(): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  }
  writeFileSync(AUTO_PUSH_SCRIPT_FILE, buildWrapperScript(), { encoding: "utf-8", mode: 0o755 });
}

function installLaunchd(hour: number, minute: number): void {
  // Ensure LaunchAgents directory exists
  const launchdDir = dirname(LAUNCHD_PLIST_PATH);
  if (!existsSync(launchdDir)) {
    mkdirSync(launchdDir, { recursive: true });
  }

  writeWrapperScript();
  writeFileSync(LAUNCHD_PLIST_PATH, buildPlist(hour, minute), { encoding: "utf-8" });

  try {
    execSync(`launchctl load "${LAUNCHD_PLIST_PATH}"`, { stdio: "ignore" });
  } catch {
    // launchctl load may fail if already loaded — that's fine
  }
}

function installCron(hour: number, minute: number): void {
  writeWrapperScript();

  const entry = `${minute} ${hour} * * * ${AUTO_PUSH_SCRIPT_FILE} >> ${AUTO_PUSH_LOG_FILE} 2>&1 ${CRON_TAG}`;

  let existing = "";
  try {
    existing = execSync("crontab -l 2>/dev/null", { encoding: "utf-8" });
  } catch {
    // No existing crontab — start fresh
  }

  // Remove any existing straude entry, then append
  const filtered = existing
    .split("\n")
    .filter((line) => !line.includes(CRON_TAG))
    .join("\n");
  const newCrontab = (filtered.endsWith("\n") ? filtered : filtered + "\n") + entry + "\n";

  execSync(`echo ${JSON.stringify(newCrontab)} | crontab -`, { stdio: "ignore" });
}

function uninstallLaunchd(): void {
  if (existsSync(LAUNCHD_PLIST_PATH)) {
    try {
      execSync(`launchctl unload "${LAUNCHD_PLIST_PATH}"`, { stdio: "ignore" });
    } catch {
      // May not be loaded — that's fine
    }
    unlinkSync(LAUNCHD_PLIST_PATH);
  }
  if (existsSync(AUTO_PUSH_SCRIPT_FILE)) {
    unlinkSync(AUTO_PUSH_SCRIPT_FILE);
  }
}

function uninstallCron(): void {
  let existing = "";
  try {
    existing = execSync("crontab -l 2>/dev/null", { encoding: "utf-8" });
  } catch {
    return; // No crontab — nothing to remove
  }

  if (!existing.includes(CRON_TAG)) return;

  const filtered = existing
    .split("\n")
    .filter((line) => !line.includes(CRON_TAG))
    .join("\n");

  if (filtered.trim() === "") {
    // Empty crontab — remove it entirely
    try {
      execSync("crontab -r 2>/dev/null", { stdio: "ignore" });
    } catch {
      // Already empty — fine
    }
  } else {
    execSync(`echo ${JSON.stringify(filtered)} | crontab -`, { stdio: "ignore" });
  }

  if (existsSync(AUTO_PUSH_SCRIPT_FILE)) {
    unlinkSync(AUTO_PUSH_SCRIPT_FILE);
  }
}

export function installScheduler(time: string, scheduler: "launchd" | "cron"): void {
  const { hour, minute } = parseTime(time);

  if (scheduler === "launchd") {
    installLaunchd(hour, minute);
  } else {
    installCron(hour, minute);
  }
}

export function uninstallScheduler(scheduler: "launchd" | "cron"): void {
  if (scheduler === "launchd") {
    uninstallLaunchd();
  } else {
    uninstallCron();
  }
}

// Exported for testing
export { parseTime as _parseTime, buildWrapperScript as _buildWrapperScript, buildPlist as _buildPlist };
