/** Country-to-region mapping for leaderboard filtering */
export const COUNTRY_TO_REGION: Record<string, string> = {
  // North America
  US: "north_america", CA: "north_america", MX: "north_america",
  GT: "north_america", BZ: "north_america", SV: "north_america",
  HN: "north_america", NI: "north_america", CR: "north_america",
  PA: "north_america", CU: "north_america", JM: "north_america",
  HT: "north_america", DO: "north_america", TT: "north_america",
  BB: "north_america", BS: "north_america", PR: "north_america",

  // South America
  BR: "south_america", AR: "south_america", CL: "south_america",
  CO: "south_america", PE: "south_america", VE: "south_america",
  EC: "south_america", BO: "south_america", PY: "south_america",
  UY: "south_america", GY: "south_america", SR: "south_america",

  // Europe
  GB: "europe", DE: "europe", FR: "europe", ES: "europe",
  IT: "europe", NL: "europe", PL: "europe", SE: "europe",
  NO: "europe", DK: "europe", FI: "europe", CH: "europe",
  AT: "europe", BE: "europe", IE: "europe", PT: "europe",
  CZ: "europe", RO: "europe", HU: "europe", UA: "europe",
  GR: "europe", HR: "europe", SK: "europe", BG: "europe",
  RS: "europe", LT: "europe", LV: "europe", EE: "europe",
  SI: "europe", IS: "europe", LU: "europe", MT: "europe",

  // Asia
  CN: "asia", JP: "asia", KR: "asia", IN: "asia",
  SG: "asia", ID: "asia", TH: "asia", VN: "asia",
  MY: "asia", PH: "asia", TW: "asia", HK: "asia",
  IL: "asia", AE: "asia", SA: "asia", PK: "asia",
  BD: "asia", LK: "asia", NP: "asia", KZ: "asia",
  UZ: "asia", MM: "asia", KH: "asia", LA: "asia",

  // Africa
  NG: "africa", ZA: "africa", EG: "africa", KE: "africa",
  GH: "africa", TZ: "africa", ET: "africa", MA: "africa",
  TN: "africa", DZ: "africa", UG: "africa", RW: "africa",
  SN: "africa", CI: "africa", CM: "africa", MZ: "africa",

  // Oceania
  AU: "oceania", NZ: "oceania", FJ: "oceania", PG: "oceania",
  WS: "oceania", TO: "oceania",
};

/** ISO 3166-1 alpha-2 code → country name, sorted alphabetically by name. */
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "DZ", name: "Algeria" },
  { code: "AR", name: "Argentina" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BS", name: "Bahamas" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brazil" },
  { code: "BG", name: "Bulgaria" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CZ", name: "Czechia" },
  { code: "DK", name: "Denmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GT", name: "Guatemala" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KR", name: "South Korea" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MY", name: "Malaysia" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "Mexico" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NG", name: "Nigeria" },
  { code: "NO", name: "Norway" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "RO", name: "Romania" },
  { code: "RW", name: "Rwanda" },
  { code: "WS", name: "Samoa" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "ZA", name: "South Africa" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UG", name: "Uganda" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
];

/** Convert an ISO 3166-1 alpha-2 code to a flag emoji. */
export function countryFlag(code: string): string {
  const upper = code.toUpperCase();
  const cp1 = 0x1f1e6 + upper.charCodeAt(0) - 65;
  const cp2 = 0x1f1e6 + upper.charCodeAt(1) - 65;
  return String.fromCodePoint(cp1, cp2);
}

export const REGIONS = [
  { value: "north_america", label: "North America" },
  { value: "south_america", label: "South America" },
  { value: "europe", label: "Europe" },
  { value: "asia", label: "Asia" },
  { value: "africa", label: "Africa" },
  { value: "oceania", label: "Oceania" },
] as const;

export type Region = (typeof REGIONS)[number]["value"];
