/** Country-to-region mapping for leaderboard filtering */
export const COUNTRY_TO_REGION: Record<string, string> = {
  // North America & Caribbean
  US: "north_america", CA: "north_america", MX: "north_america",
  GT: "north_america", BZ: "north_america", SV: "north_america",
  HN: "north_america", NI: "north_america", CR: "north_america",
  PA: "north_america", CU: "north_america", JM: "north_america",
  HT: "north_america", DO: "north_america", TT: "north_america",
  BB: "north_america", BS: "north_america", PR: "north_america",
  AG: "north_america", DM: "north_america", GD: "north_america",
  KN: "north_america", LC: "north_america", VC: "north_america",

  // South America
  BR: "south_america", AR: "south_america", CL: "south_america",
  CO: "south_america", PE: "south_america", VE: "south_america",
  EC: "south_america", BO: "south_america", PY: "south_america",
  UY: "south_america", GY: "south_america", SR: "south_america",

  // Europe
  GB: "europe", DE: "europe", FR: "europe", ES: "europe",
  IT: "europe", NL: "europe", PL: "europe", SE: "europe",
  NO: "europe", DK: "europe", FI: "europe", CH: "europe",
  AT: "europe", BE: "europe", IE: "europe", PT: "europe",
  CZ: "europe", RO: "europe", HU: "europe", UA: "europe",
  GR: "europe", HR: "europe", SK: "europe", BG: "europe",
  RS: "europe", LT: "europe", LV: "europe", EE: "europe",
  SI: "europe", IS: "europe", LU: "europe", MT: "europe",
  AD: "europe", AL: "europe", BA: "europe", BY: "europe",
  CY: "europe", GE: "europe", LI: "europe", MC: "europe",
  MD: "europe", ME: "europe", MK: "europe", SM: "europe",
  TR: "europe", VA: "europe",

  // Asia
  CN: "asia", JP: "asia", KR: "asia", IN: "asia",
  SG: "asia", ID: "asia", TH: "asia", VN: "asia",
  MY: "asia", PH: "asia", TW: "asia", HK: "asia",
  IL: "asia", AE: "asia", SA: "asia", PK: "asia",
  BD: "asia", LK: "asia", NP: "asia", KZ: "asia",
  UZ: "asia", MM: "asia", KH: "asia", LA: "asia",
  AF: "asia", AM: "asia", AZ: "asia", BH: "asia",
  BN: "asia", BT: "asia", IQ: "asia", IR: "asia",
  JO: "asia", KG: "asia", KP: "asia", KW: "asia",
  LB: "asia", MN: "asia", MV: "asia", OM: "asia",
  PS: "asia", QA: "asia", SY: "asia", TJ: "asia",
  TL: "asia", TM: "asia", YE: "asia",

  // Africa
  NG: "africa", ZA: "africa", EG: "africa", KE: "africa",
  GH: "africa", TZ: "africa", ET: "africa", MA: "africa",
  TN: "africa", DZ: "africa", UG: "africa", RW: "africa",
  SN: "africa", CI: "africa", CM: "africa", MZ: "africa",
  AO: "africa", BF: "africa", BI: "africa", BJ: "africa",
  BW: "africa", CD: "africa", CF: "africa", CG: "africa",
  CV: "africa", DJ: "africa", ER: "africa", GA: "africa",
  GM: "africa", GN: "africa", GQ: "africa", GW: "africa",
  KM: "africa", LR: "africa", LS: "africa", LY: "africa",
  MG: "africa", ML: "africa", MR: "africa", MU: "africa",
  MW: "africa", NA: "africa", NE: "africa", SC: "africa",
  SD: "africa", SL: "africa", SO: "africa", SS: "africa",
  ST: "africa", SZ: "africa", TD: "africa", TG: "africa",
  ZM: "africa", ZW: "africa",

  // Oceania
  AU: "oceania", NZ: "oceania", FJ: "oceania", PG: "oceania",
  WS: "oceania", TO: "oceania", FM: "oceania", KI: "oceania",
  MH: "oceania", NR: "oceania", PW: "oceania", SB: "oceania",
  TV: "oceania", VU: "oceania",
};

/** ISO 3166-1 alpha-2 code → country name, sorted alphabetically by name. */
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cape Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "CD", name: "DR Congo" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

/** Convert an ISO 3166-1 alpha-2 code to a flag emoji. */
export function countryFlag(code: string): string {
  const upper = code.toUpperCase();
  const cp1 = 0x1f1e6 + upper.charCodeAt(0) - 65;
  const cp2 = 0x1f1e6 + upper.charCodeAt(1) - 65;
  return String.fromCodePoint(cp1, cp2);
}

export const REGIONS = [
  { value: "north_america", label: "North America" },
  { value: "south_america", label: "South America" },
  { value: "europe", label: "Europe" },
  { value: "asia", label: "Asia" },
  { value: "africa", label: "Africa" },
  { value: "oceania", label: "Oceania" },
] as const;

export type Region = (typeof REGIONS)[number]["value"];
